// AUTO-GENERATED by the manggaleh CLI (`mg types`). DO NOT edit manually.
// Regenerate: `mg types --project <slug> --env <env> --out <file>`

export interface Announcements {
  id: string;
  created_by?: string | null;
  title: string;
  message: string;
  expiry_date: string;
  published?: boolean | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface AppUsers {
  id: string;
  user_id: string;
  created_by?: string | null;
  name: string;
  email: string;
  role: string;
  admin_level?: string | null;
  active?: boolean | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface Appointments {
  id: string;
  patient_user_id: string;
  created_by?: string | null;
  clinic_id: string;
  service_type_id: string;
  therapist_id: string;
  date: string;
  start: string;
  end: string;
  for_member_id?: string | null;
  for_member_name?: string | null;
  status: string;
  source?: string | null;
  note?: string | null;
  cancelled_by?: string | null;
  cancellation_reason_id?: string | null;
  cancellation_note?: string | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface AuditLog {
  id: string;
  created_by?: string | null;
  actor_user_id?: string | null;
  actor_name?: string | null;
  action: string;
  detail?: string | null;
  at: string;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface CancellationReasons {
  id: string;
  created_by?: string | null;
  label: string;
  active?: boolean | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface Clinics {
  id: string;
  created_by?: string | null;
  name: string;
  address?: string | null;
  contact?: string | null;
  active?: boolean | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface CreditTransfers {
  id: string;
  created_by?: string | null;
  from_user_id: string;
  to_user_id: string;
  sessions: number;
  original_package_id?: string | null;
  recipient_package_id?: string | null;
  expiry_date?: string | null;
  reversed?: boolean | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface FamilyMembers {
  id: string;
  owner_user_id: string;
  created_by?: string | null;
  name: string;
  relationship?: string | null;
  is_child?: boolean | null;
  linked_user_id?: string | null;
  parent_user_id?: string | null;
  status: string;
  family_group_id?: string | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface Friends {
  id: string;
  requester_user_id: string;
  created_by?: string | null;
  addressee_user_id: string;
  status: string;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface PackageDefinitions {
  id: string;
  created_by?: string | null;
  name: string;
  sessions: number;
  validity_days: number;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface PackageUsage {
  id: string;
  created_by?: string | null;
  patient_package_id: string;
  appointment_id?: string | null;
  member_name?: string | null;
  date: string;
  recorded_by?: string | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface PatientPackages {
  id: string;
  owner_user_id: string;
  created_by?: string | null;
  definition_id?: string | null;
  name: string;
  total_sessions: number;
  remaining: number;
  assign_date: string;
  expiry_date: string;
  status: string;
  source_package_id?: string | null;
  transferred_from_user_id?: string | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface PatientProfiles {
  id: string;
  user_id: string;
  created_by?: string | null;
  date_of_birth?: string | null;
  gender?: string | null;
  address?: string | null;
  emergency_contact?: string | null;
  family_group_id?: string | null;
  active?: boolean | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface ProductPurchases {
  id: string;
  patient_user_id: string;
  created_by?: string | null;
  product_id?: string | null;
  product_name?: string | null;
  unit_price_at_sale?: number | null;
  quantity?: number | null;
  purchase_date: string;
  estimated_follow_up_date?: string | null;
  follow_up_status?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface Products {
  id: string;
  created_by?: string | null;
  name: string;
  category?: string | null;
  price: number;
  active?: boolean | null;
  notes?: string | null;
  image_object_ids?: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface ServiceTypes {
  id: string;
  created_by?: string | null;
  name: string;
  duration_minutes: number;
  active?: boolean | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface SubAdminPermissions {
  id: string;
  created_by?: string | null;
  key?: string | null;
  manage_booking?: boolean | null;
  appointment_management?: boolean | null;
  manage_clinics?: boolean | null;
  manage_therapists?: boolean | null;
  manage_patients?: boolean | null;
  manage_products?: boolean | null;
  manage_services?: boolean | null;
  manage_cancellation_reasons?: boolean | null;
  manage_announcements?: boolean | null;
  manage_follow_up?: boolean | null;
  reports_services?: boolean | null;
  reports_products?: boolean | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface TherapistAvailability {
  id: string;
  created_by?: string | null;
  therapist_id: string;
  clinic_id: string;
  date: string;
  start: string;
  end: string;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface Therapists {
  id: string;
  created_by?: string | null;
  name: string;
  active?: boolean | null;
  user_id?: string | null;
  created_at: string;
  updated_at: string;
  updated_by?: string | null;
}

export interface Collections {
  announcements: Announcements;
  app_users: AppUsers;
  appointments: Appointments;
  audit_log: AuditLog;
  cancellation_reasons: CancellationReasons;
  clinics: Clinics;
  credit_transfers: CreditTransfers;
  family_members: FamilyMembers;
  friends: Friends;
  package_definitions: PackageDefinitions;
  package_usage: PackageUsage;
  patient_packages: PatientPackages;
  patient_profiles: PatientProfiles;
  product_purchases: ProductPurchases;
  products: Products;
  service_types: ServiceTypes;
  sub_admin_permissions: SubAdminPermissions;
  therapist_availability: TherapistAvailability;
  therapists: Therapists;
}
