/** @type {import('tailwindcss').Config} */
// Token "Calm Clinical" — disalin dari stitch-design/calm_clinical/DESIGN.md
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#00210a',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#587979',
        'surface-container': '#f0edec',
        'secondary-fixed': '#d9e6da',
        'on-primary-fixed-variant': '#105320',
        'primary-fixed': '#bff0c8',
        'on-secondary': '#ffffff',
        outline: '#6e7979',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        'on-secondary-fixed': '#131e17',
        error: '#ba1a1a',
        'surface-container-highest': '#e5e2e1',
        secondary: '#556158',
        'secondary-container': '#d9e6da',
        'surface-dim': '#dcd9d9',
        'primary-container': '#1e9e3a',
        'on-tertiary-fixed': '#002020',
        'on-surface': '#1c1b1b',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#bdcabe',
        'on-tertiary-container': '#e6fffe',
        'surface-container-high': '#ebe7e7',
        'outline-variant': '#bdc9c8',
        'inverse-surface': '#313030',
        'surface-container-low': '#f6f3f2',
        tertiary: '#406060',
        'on-primary-container': '#eafff0',
        'error-container': '#ffdad6',
        'on-background': '#1c1b1b',
        'on-primary': '#ffffff',
        background: '#fcf9f8',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#8fe0a0',
        'on-tertiary-fixed-variant': '#2c4c4c',
        'on-secondary-fixed-variant': '#3e4a41',
        'on-secondary-container': '#5b675e',
        'tertiary-fixed': '#c6e9e9',
        surface: '#fcf9f8',
        primary: '#15772b',
        'surface-tint': '#15772b',
        'surface-variant': '#e5e2e1',
        'tertiary-fixed-dim': '#abcdcd',
        'inverse-primary': '#8fe0a0',
        'surface-bright': '#fcf9f8',
        'on-surface-variant': '#3e4949',
        // aksen pembeda klinik
        'clinic-a': '#1e9e3a',
        'clinic-b': '#406060',
        success: '#2e8b57',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xl: '64px',
        sm: '12px',
        base: '8px',
        'margin-desktop': '120px',
        md: '24px',
        xs: '4px',
        lg: '40px',
        gutter: '24px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
